spring:
  kafka:
    producer:
      client-id: Rest-producer
      bootstrap-servers: 20.251.51.7:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
